name: Test Deployment

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@dev
      - uses: actions/setup-node@dev
        with:
          node-version: 12
      - run: npm install
      - uses: JS-Devtools/npm-publish@v1
        with:
          token: ${{ secrets.TEST_AUTH_TOKEN }}
        



